---
version: '2.4'

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    volumes:
      - "./data:/var/lib/mysql"
      - "./scripts:/docker-entrypoint-initdb.d/"
    environment:
      MYSQL_ROOT_PASSWORD: secret
    ports: 
      - 3306:3306

  php:
    image: php7.3-mysql
    container_name: php
    volumes:
      - "./html:/srv/http"
    ports: 
      - 9000:9000

  www:
    image: nginx:latest
    container_name: www
    volumes:
      - "./html:/usr/share/nginx/html"
      - "./conf/nginx.conf:/etc/nginx/nginx.conf"
    ports:
      - 80:80

networks:
  default:
    external:
      name: net_1
##  net_2:
##    driver: bridge
##   name: net_2
##    ipam: 
##      config: 
##        - subnet: 172.25.0.0/24
##          gateway: 172.25.0.254